version: "2"
services:

  api:
    ports:
      - "8800:8800"
    build: .
    volumes:
      - "./src:/var/www/api/src"
      - "./scripts:/var/www/api/scripts"
      - "./config.js:/var/www/api/config.js"
      - "./package.json:/var/www/api/package.json"
      - "./tsconfig.json:/var/www/api/tsconfig.json"
      - distribution:/var/www/api/dist
      - node_modules:/var/www/api/node_modules
    depends_on:
      - db
      - rabbitmq

  db:
    ports:
      - "27017"
    image: mongo
    restart: always
    volumes:
      - database:/data/db
  rabbitmq:
      image: rabbitmq:3-management-alpine
      hostname: rabbitmq
      container_name: 'rabbitmq'
      ports:
          - 5672:5672
          - 15672:15672
      healthcheck:
        test: nc -z rabbitmq 5672
        interval: 10s
        timeout: 10s
        retries: 100
      volumes:
          - rabbitmq:/data/rabbitmq/
      
volumes:
  distribution:
  node_modules:
  database:
  rabbitmq:
